include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/shared/mocks/*.mocks.dart
    - "**/*.g.dart"
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-arguments: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    always_use_packages_imports: true
      - avoid-unused-parameters
      - newline-before-return
      - no-boolean-literal-compare
      - no-empty-block
      - require_trailing_commas
      - prefer-conditional-expressions
      - always-remove-listener
      - no-equal-then-else
      - cancel_subscriptions
      - unawaited_futures
      - close_sinks
      - file_names
      - prefer_const_constructors
      - unnecessary_parenthesis
      - avoid_dynamic_calls
      - avoid_print
      - prefer_is_empty
      - prefer_is_not_empty
      - avoid_unnecessary_containers
      - avoid_web_libraries_in_flutter
      - no_logic_in_create_state
      - prefer_const_constructors_in_immutables
      - prefer_final_fields
      - prefer_final_in_for_each
      - prefer_final_locals
      - prefer_const_declarations
      - prefer_const_literals_to_create_immutables
      - sized_box_for_whitespace
      - sort_child_properties_last
      - use_build_context_synchronously
      - use_full_hex_values_for_flutter_colors
      - use_key_in_widget_constructors
      - strict-inference
      - strict-raw-types
      - prefer_single_quotes
      - prefer_relative_imports
      - library_private_types_in_public_api
      - unnecessary_await_in_return
      - unnecessary_brace_in_string_interps
      - unnecessary_const
      - unnecessary_constructor_name
      - unnecessary_getters_setters
      - unnecessary_lambdas
      - unnecessary_late
      - unnecessary_new
      - unnecessary_null_aware_assignments
      - unnecessary_null_aware_operator_on_extension_on_nullable
      - unnecessary_null_checks
      - unnecessary_null_in_if_null_operators
      - unnecessary_nullable_for_final_variable_declarations
      - unnecessary_overrides
      - unnecessary_raw_strings
      - unnecessary_statements
      - unnecessary_string_escapes
      - unnecessary_string_interpolations
      - unnecessary_this
      - unnecessary_to_list_in_spreads
  anti-patterns:
    - long-method
    - long-parameter-list

linter:
  rules:
    require_trailing_commas: true
    cancel_subscriptions: true
    unawaited_futures: true
    close_sinks: true
    file_names: true
    prefer_const_constructors: true
    unnecessary_parenthesis: true
    avoid_dynamic_calls: true
    avoid_print: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    library_private_types_in_public_api: false
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
